### ISSUE TITLE
[REQUEST]: Export media data separately from database and tables

### ISSUE THREAD

**Issue by kathywake23** [PhenoApps/Field-Book#1018]
### Description

Would like to be able to separately export the media data independent of the table and database using the export button.

### Alternatives

I'm currently crashing the system until I can get the media to download with the table. Tried going into Palma to manually retrieve the files, but it proved to be time consuming.

**Comment by trife** [comment]
Since images can be copied directory from the device, I'm not sure I see the value of adding a separate media export that would likely have the same issues you're currently experiencing with the bundle export. Those issues may be related to #995 but at some point, you're just going to have too many images to export these alongside everything else.
