### ISSUE TITLE
[REQUEST]: Zebra label print tally

### ISSUE THREAD

**Issue by ramierop** [PhenoApps/Field-Book#1043]
### Description

I would like to be able to see how many labels were created under the table output when exporting. 

Talking with @bellerbrock I believe there is a way that the number of labels printed using Zebra Label Print trait could be displayed in the export table. From what I remember, the database stores this data. 

Where this would be handy is when bringing bins/lugs in from field, I can tell the crew how many lugs to expect for a given clone. 

### Alternatives

Manual tally on number of lugs, or WAG, ex "should be 2, but could be 1 or 3"

**Comment by bellerbrock** [comment]
Hey @ramierop, I had the app start storing the label count as part of a [some print trait changes back in April](https://github.com/PhenoApps/Field-Book/pull/944). I thought there may be another step to ensure it's included on export, but that's actually already happening automatically.

So just use any version of 5.6 released since April and you should be good to go.
