### ISSUE TITLE
[BUG] standardize DateTimeFormatter

### ISSUE THREAD

**Issue by BrapiCoordinatorSelby** [PhenoApps/Field-Book#195]
**Describe the bug**
While reviewing #183 I found at least 4 different DateTimeFormatter strings ranging from `...mm:ssZ` (no milliseconds) to `...mm:ss.SSSZZZZZ` (an invalid format and should throw an error) 

**To Reproduce**
NA

**Expected behavior**
All timestamps in the code and db should have the same format, probably `yyyy-MM-dd HH:mm:ss.SSSZ`

**Screenshots**
NA

**Device Info (please complete the following information):**
NA

**Additional context**
NA

**Comment by trife** [comment]
`SSSZZZZZ` was used as a result of a few intersecting errors: `SSSZ` causes Excel to interpret the time as a formula and led to issues for several users, `SSSXXX` (which adds a colon to the timezone) isn't supported on pre-Nougat devices and led to crashes for several other users. I believe `SSSZZZZZ` is an Android specific implementation (because of course it is).

I think other timestamps usages are all internal so they haven't been completely standardized, but we can review them.

**Comment by trife** [comment]
I think this is resolved in #207 and #203
