### ISSUE TITLE
[BUG] V2 study import doesn't add traits for observations

### ISSUE THREAD

**Issue by nickpalladino** [PhenoApps/Field-Book#228]
**Describe the bug**
If you use the v2 import you will always have 0 traits but if you use the v1 import you'll have the number of traits there are observations for. Ultimately we would like to change this anyways to have traits associated with the study without the need for existing observations. I haven't looked into this to see what's going on yet whether in Field Book or breedbase.

**To Reproduce**
1. Import study for v2 with observations and see no traits
2. Import study for v1 with observations and see traits

**Expected behavior**
Would actually like to add new functionality to add traits in brapi server and have field book pick those up without observations

**Device Info (please complete the following information):**
 - Model: [e.g. Pixel 3a API 30]
 - Field Book Version [brapi_v2]

**Comment by BrapiCoordinatorSelby** [comment]
I think this is a Breedbase specific issue. When importing a Study, Field Book will call `GET /variables?studyDbId=studyDbId` and collect traits that are associated with that study. I think Breedbase is purposefully ignoring this request in its v2 endpoint. I tested with the BrAPI Test Server and traits are being imported successfully with a study. 

I also think your expected behavior is an issue for the BrAPI spec. When POSTing a new variable, there is no way to associate it with a study. A database might have a custom UI to associate variables and studies without observations, but that is not possible in pure BrAPI V2.0.  

As far as I can tell, Field Book is acting as intended for this issue.

**Comment by trife** [comment]
Closed. If this ends up being something related to Field Book @nickpalladino can reopen.
