### ISSUE TITLE
[BUG] Improper setting of descriptiveOntologyTerm for FieldBookImage

### ISSUE THREAD

**Issue by ctucker3** [PhenoApps/Field-Book#286]
If you look at the `DataHelper` in v4.5, https://github.com/PhenoApps/Field-Book/blob/f4f4612e3ae5aafeca51e8f2770f8a2f6d5bd094/app/src/main/java/com/fieldbook/tracker/database/DataHelper.java, at the `getImageObservations` method you will see that `descriptiveOntologyTerm` was being set to `traits.external_db_id`. 

If you look at the `Observations` dao in the newest code, https://github.com/PhenoApps/Field-Book/blob/master/app/src/main/java/com/fieldbook/tracker/database/dao/ObservationDao.kt, at the `getHostImageObservations` method (line 69) you'll see that `descriptiveOntologyTerm` is being set to the `observationUnitName`. 

This is causing issues in BreedBase because it depends on that term to find the variable the image belongs to. 

**Expected behavior**
The `descriptiveOntologyTerms` should contain the external trait db id.

**Comment by ctucker3** [comment]
I'll grab this one.

**Comment by nahuel-soldevilla** [comment]
Sorry for posting this here, it's just that @ctucker3 you mention how this is being handled in breedbase and we have something similar, and some things we want to improve / are not comfortable with.
Rather than a question(s) is more like sharing our implementation details, in case there's better way to handle this.

The main problem we have is that we are storing images using some of the internal mechanism we use to store observations (It seems Field book does something similar), and we associate them with a trait too, to be able to collect them using field book and them export them using the brapi flow, but then inside BMS these "observations" (we store the file name by the way as observation value, and the image content is stored elsewhere, e.g aws s3) cannot be handled in the same way as other normal observations, and so we need to hide them in a lot of places.
So the first question is "Does something similar happen in breedbase? what happens after the images are pushed there?"

Secondly, about the trait synchronization process, I guess you are in the same situation as we are, where you need to manually change the trait to Image type after the import?
Relates to https://github.com/plantbreeding/API/issues/476
If you have a better approach for that, please let us know

Lastly, and this is probably less relevant, we were discussing today with @mcrimi and @clarysabel some ideas about not having a trait id or variable id for images inside BMS, and link them only to an observation unit, but of course this is not possible because we won't be able to sync them with fieldbook as they need to be imported first as a trait from a study.

Anyway, not waiting specifically for an answer, just wanted to share this info here in case you (or anyone else) has some insight into this.

Tagging @trife @BrapiCoordinatorSelby @lukasmueller
who may be interested in this or can probably weigh in.

**Comment by lukasmueller** [comment]
Hi Nahuel,

in Breedbase images are not stored as a observation, but are tagged as such in Fieldbook. Instead, the images are associated directly with the observation units through a special linking table. The images can also be associated to a cvterm describing the image.

Let me know if that answers your questions at least partially. We could have a brief meeting about this, as it is important for BrAPI how things are handled.

thanks and cheers
Lukas

**Comment by nahuel-soldevilla** [comment]
Hi @lukasmueller, thanks for the feedback, yes, that answers part of my question.
Yes, we'll be glad to have that meeting, pinging @mcrimi who was also thinking about this.

**Comment by ctucker3** [comment]
> Secondly, about the trait synchronization process, I guess you are in the same situation as we are, where you need to manually change the trait to Image type after the import?

Yep, we do the same thing. We don't have a good solution right now. To me it seems like the main issue is that brapi does not define an image as a variable data type, but Field Book does.

**Comment by nahuel-soldevilla** [comment]
Leaving also a follow-up here about the meeting and discussion above, and some implementation changes in BMS that would make it more aligned with Breedbase implementation:

- We switched the approach to link images to observation units (image is no longer an observation by itself)
- Images will be associated also to cvterm/traits
- We discarded the idea of having a special datatype for Image, so any trait can be converted to Photo in the Fieldbook app and exported to BMS, the drawback being that for the said trait we can no longer take normal measurements in Fieldbook, just photos. In BMS it will possible to have both for the same trait
