### ISSUE TITLE
[BUG] Field Book prints 9 blank labels for each successful label

### ISSUE THREAD

**Issue by trife** [PhenoApps/Field-Book#494]
![image](https://user-images.githubusercontent.com/1869534/187472154-65a24562-2e3a-43ad-9b9d-34ee18bc332c.png)

**Comment by bellerbrock** [comment]
I did some testing with a printer exhibiting the same symptoms. The problem is external to Fieldbook, it's caused by a combination of outdated firmware and incorrect media type setting (should be set to MARK). Here are the steps to fix the problem, I'll include them in the print trait documentation on readthedocs as well:

1. Install the [Zebra Printer Setup Utility](https://play.google.com/store/apps/details?id=com.zebra.printersetup) on an android device that can connect to the printer.
2. Download the latest firmware for the mobile printer model from the [Zebra support page](https://www.zebra.com/us/en/support-downloads/printers.html), unzip it, then send the unzipped `.zpl` file to the printer using the **Available Files** option in the Zebra Printer Setup Utility.
3. Now that the firmware is updated, set the media type to `MARK` through the **Media Settings** option in the Zebra Printer Setup Utility.
