### ISSUE TITLE
[BUG]: Date trait deleting

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#678]
### Description

See attached video.

https://github.com/PhenoApps/Field-Book/assets/36375878/6ae8f7f1-fb73-4b13-bd9f-481e2a759e89

### Field Book version

5.4.0

**Comment by trife** [comment]
Does this only happen with repeated measures enabled?

-Trevor
Sent from mobile

On Jul 18, 2023 7:37 PM, Chris Hernandez ***@***.***> wrote:
Description See attached video. https: //github. com/PhenoApps/Field-Book/assets/36375878/6ae8f7f1-fb73-4b13-bd9f-481e2a759e89 Expected behavior No response Field Book version 5. 4. 0 — Reply to this email directly, view it on GitHub ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
Use caution when opening links or attachments if you do not recognize the sender.

ZjQcmQRYFpfptBannerEnd

Description

See attached video.

https://github.com/PhenoApps/Field-Book/assets/36375878/6ae8f7f1-fb73-4b13-bd9f-481e2a759e89<https://urldefense.com/v3/__https://github.com/PhenoApps/Field-Book/assets/36375878/6ae8f7f1-fb73-4b13-bd9f-481e2a759e89__;!!PTd7Sdtyuw!UZKDFdXa36SpwYxDDtdyROeRp6rrS5lPBQwMCfqwJ075eFIu-4Dffj2VaiZUMJAknNt_JsZIWl5RERBLf7JgvJlX2w$>

Expected behavior

No response

Field Book version

5.4.0

**Comment by ch728** [comment]
Not sure, I will check this morning

**Comment by ch728** [comment]
It seems to be still happening when repeated measures is disabled, but the behavior is a little different now. I will send another video that shows it.

**Comment by trife** [comment]
I'm completely unable to replicate this so not sure if it's connected to brapi-pulled info only. Can you export your database from this device and email me the zipped file?

**Comment by trife** [comment]
Do you see the same behavior if you turn off the "Day of year" setting and then try to save the date? This might be a Samsung date formatting issue.

**Comment by chaneylc** [comment]
I was able to reproduce the problem and created a PR #709 
Repeated values wasn't displaying the dates correctly, we can keep this issue open if it's also occurring in the default mode, but I wasn't able to reproduce it there.
