### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by splGH** [PhenoApps/Field-Book#973]
### Description

I am using the experimental feature that enables audio entry of text for a trait value entry. I am using the sample data and trait field 'notes'. When I record a phrase, it is entered once and then the app verbalizes what I said, which gets added and verbalized, and this repeats until I exit the app. This only happens if I use the microphone icon on the keyboard. If I use the google voice option, it records correctly.

### Expected behavior

The only text that should be transcribed is what I spoke and not what the app repeated back. It would be nice if I could use the keyboard microphone so that I can either type or speak. Perhaps for now the keyboard microphone should be inactive when the voice to text option is chosen.

### Field Book version

5.6.18

**Comment by trife** [comment]
@splGH I'm a bit confused here. There's an experimental feature that records a running audio file but nothing in the Experimental settings related to audio input for a trait value entry.

I'm also unclear on the difference between the microphone icon on the keyboard and the google voice option since these are the same thing on most devices. Maybe add a few screenshots of what you're seeing? I don't think it's possible for us to control the keyboard UI and I'm not sure that it's possible for us to identify that data has been input via audio.

**Comment by splGH** [comment]
![Screenshot_20240517_132037_Field Book](https://github.com/PhenoApps/Field-Book/assets/170051429/934ca5d7-bb08-418f-a773-0ab168f35857)
![Screenshot_20240517_132557_Field Book](https://github.com/PhenoApps/Field-Book/assets/170051429/ace23955-7431-4223-88ef-fd2f45eefa56)
[Scan 17 May 24 · 03·04·47.pdf](https://github.com/PhenoApps/Field-Book/files/15358535/Scan.17.May.24.03.04.47.pdf)

**Comment by trife** [comment]
@splGH - This is a feature of your system not something that we can control. The experimental feature you enabled (top right in your screenshots) is completely unrelated to this behavior.
